In [12]:
import pandas as pd
import numpy as np

In [13]:
a = pd.read_excel('house_rent_no_duplicate.xlsx')
a

   ROOM   NAME MONTH  RENT  EXTRA
0   101    LEE   JAN    30      2
1   102   PARK   JAN    30      2
2   103  CHUNG   JAN    50      5
3   104    YUN   JAN    45      5
4   101    LEE   FEB    30      2
5   102   PARK   FEB    30      2
6   103  CHUNG   FEB    50      5
7   104    YUN   FEB    45      5

# pd.pivot

In [14]:
b = pd.pivot(a, index='ROOM', columns='MONTH', values='RENT')
# b = a.pivot(index='ROOM', columns='MONTH', values='RENT')
b

MONTH  FEB  JAN
ROOM
101     30   30
102     30   30
103     50   50
104     45   45

# pd.pivot vs pd.pivot_table

For anyone who is still interested in the difference between pivot and pivot_table, there are mainly two differences:

    pivot_table is a generalization of pivot that can handle duplicate values for one pivoted index/column pair. Specifically, you can give pivot_table a list of aggregation functions using keyword argument aggfunc. The default aggfunc of pivot_table is numpy.mean.

    pivot_table also supports using multiple columns for the index and column of the pivoted table. A hierarchical index will be automatically generated for you.

[stackoverflow](https://stackoverflow.com/questions/30960338/pandas-difference-between-pivot-and-pivot-table-why-is-only-pivot-table-workin)

In [15]:
a = pd.read_excel('house_rent_duplicate.xlsx')
a

    ROOM   NAME MONTH  RENT  EXTRA
0    101    LEE   JAN    30      2
1    101    KIM   JAN    30      2
2    102   PARK   JAN    30      2
3    102    LEE   JAN    30      2
4    103  CHUNG   JAN    50      5
5    104    YUN   JAN    45      5
6    101    LEE   FEB    30      2
7    101    KIM   FEB    30      2
8    102   PARK   FEB    30      2
9    102    LEE   FEB    30      2
10   103  CHUNG   FEB    50      5
11   104    YUN   FEB    45      5

# pd.pivot not working

In [16]:
b = pd.pivot(a, index='ROOM', columns='MONTH', values='RENT')
b

ValueError: Index contains duplicate entries, cannot reshape

# pd.pivot_table works

In [17]:
b = pd.pivot_table(a, index='ROOM', columns='MONTH', values='RENT')
b

MONTH  FEB  JAN
ROOM
101     30   30
102     30   30
103     50   50
104     45   45

# aggfunc

In [18]:
b = pd.pivot_table(a, index='ROOM', columns='MONTH', values='RENT',
                  aggfunc=np.mean)
b

MONTH  FEB  JAN
ROOM
101     30   30
102     30   30
103     50   50
104     45   45

In [19]:
b = pd.pivot_table(a, index='ROOM', columns='MONTH', values='RENT',
                  aggfunc=np.sum)
b

MONTH  FEB  JAN
ROOM
101     60   60
102     60   60
103     50   50
104     45   45

In [20]:
b = pd.pivot_table(a, index='ROOM', columns='MONTH', values='RENT',
                  aggfunc=np.sum,
                  margins=True, margins_name='TOTAL')
b

MONTH  FEB  JAN  TOTAL
ROOM
101     60   60    120
102     60   60    120
103     50   50    100
104     45   45     90
TOTAL  215  215    430

# multilayer index and columns

In [21]:
b = pd.pivot_table(a, index=['ROOM','NAME'], columns='MONTH', values='RENT')
b

MONTH       FEB  JAN
ROOM NAME
101  KIM     30   30
     LEE     30   30
102  LEE     30   30
     PARK    30   30
103  CHUNG   50   50
104  YUN     45   45

In [22]:
b = pd.pivot_table(a, columns=['ROOM','NAME'], index='MONTH', values='RENT')
b

ROOM  101     102        103 104
NAME  KIM LEE LEE PARK CHUNG YUN
MONTH
FEB    30  30  30   30    50  45
JAN    30  30  30   30    50  45

# Reference

Ryan Noonan
[Python Pandas - Pivot and Pivot Table](https://www.youtube.com/watch?v=PMKuZoQoYE0)
[Python Pandas Pivot Table Example](https://www.youtube.com/watch?v=fDCn5myCBOc)